README.md
=> fix typo in README.md: "fuassetsnds" -> "assets"

src/bridges/element/ElementBridge.sol, src/bridges/element/interfaces/ITranche.sol, src/test/element/Element.t.sol, src/test/element/Heap.t.sol
Check that new interactions are not already expired
=> Bug fix for expiry verification

package.json
Updated version number to 0.1.23
=> Updated version number to 0.1.23

src/bridges/liquity/StabilityPoolBridge.sol, src/bridges/liquity/StakingBridge.sol, src/bridges/liquity/TroveBridge.sol, src/test/liquity/TroveBridge.t.sol
I decreased deployment and runtime gas costs by replacing require statements with custom errors. As an example the gas saving in deployment cost for StabilityPoolBridge.sol 95105 gas.
=> Gas optimizations of Liquity bridges

package.json, src/bridges/element/ElementBridge.sol, src/test/element/Element.t.sol
In this pr the Element bridge emits the gas used for the convert and finalise operations in the generated logs
=> Emit gas consumption in logs for Element bridge

package.json, src/client/aztec/eth_address/eth_address.ts, src/client/aztec/eth_address/index.ts, src/client/aztec/provider/ethereum_provider.ts, src/client/aztec/provider/index.ts, src/client/aztec/provider/web3_provider.ts, src/client/aztec/random/index.ts, src/client/element/element-bridge-data.test.ts, src/client/element/element-bridge-data.ts, src/client/lido/lido-bridge-data.test.ts, src/client/lido/lido-bridge-data.ts, src/client/mstable/mstable-bridge-data.test.ts, src/client/mstable/mstable-bridge-data.ts, src/client/uniswapv3/async-uniswap-bridge-data.ts, src/client/uniswapv3/uni-bridge-data.test.ts, src/client/uniswapv3/uniswap-bridge-data.ts, src/test/uniswapv3/Uniswap.t.sol, yarn.lock
This PR refactors the process of bridge data construction to abtract typechain away from the client of the class.
=> Refactored bridge data construction

package.json, src/client/element/element-bridge-data.test.ts, src/client/element/element-bridge-data.ts
This PR simply renames a parameter passed to the Element bridge data class to make it more descriptive for users of the class
=> Renamed paramter

src/test/liquity/TroveBridge.t.sol
I introduced a bug to Liquity tests in PR https://github.com/AztecProtocol/aztec-connect-bridges/pull/71 and I am fixing it with this PR.
=> test: fixed TroveBridge full flow test

.gitignore, package.json, yarn.lock
I setup linting and formatting commands since formatting is very messy across this repository. I didn't yet run the formatting because it would cause conflicts in Lasse's PR https://github.com/AztecProtocol/aztec-connect-bridges/pull/21 . All the other PRs are strictly additive (not changing any current fails) and hence should be unaffected.
Unless someone disagrees once Lasse's PR is merged I will rebase this branch on master and run the formatting.
=> chore: linting + formatting commands + dependencies

src/bridges/example/ExampleBridge.sol, src/test/bridges/example/Example.t.sol
General improvements of example.
=> feat: improved example

package.json, src/client/curve/curve-steth/curve-bridge-data.test.ts, src/client/curve/curve-steth/curve-bridge-data.ts
Bridge data helper for the curve stEth bridge.
=> Curve steth bridge data

.circleci/config.yml, .solhintignore, package.json
Please provide a paragraph or two giving a summary of the change, including relevant motivation and context.
=> Linter in CI, command cleanup, disabled Ace tests

.husky/pre-commit, package.json, yarn.lock
Configured husky to run prettier.
=> Configured husky to run prettier

src/bridges/donation/DonationBridge.sol, src/client/donation/donation-bridge-data.ts, src/specs/donation/readme.md, src/test/bridges/donation/DonateBridgeE2E.t.sol
A small bridge that allows a group of users within Aztec to make a donation to an L1 address (group-send).
=> Donation bridge

src/bridges/uniswap/UniswapBridge.sol, src/specs/uniswap/readme.md
=> docs: Uniswap bridge spec

README.md, src/aztec/interfaces/IRollupProcessor.sol, src/client/element/element-bridge-data.test.ts, src/client/element/element-bridge-data.ts, src/specs/TEMPLATE.md, src/test/aztec/base/BridgeTestBase.sol, src/test/aztec/base/EncodeBridgeId.t.sol, src/test/bridges/aave/AaveLendingBridge.t.sol, src/test/bridges/aceofzk/AceOfZk.t.sol, src/test/bridges/compound/Compound.t.sol, src/test/bridges/curve/CurveStEthBridge.t.sol, src/test/bridges/element/aztecmocks/RollupProcessor.sol, src/test/bridges/example/ExampleE2E.t.sol, src/test/bridges/lido/Lido.t.sol, src/test/bridges/uniswap/UniswapBridgeE2E.t.sol
Renamed bridgeId to bridgeCallData.
=> Renamed bridgeId to bridgeCallData

src/client/aave/aave-bridge-data.test.ts, src/client/aave/aave-bridge-data.ts, src/client/bridge-data.ts, src/client/compound/compound-bridge-data.test.ts, src/client/compound/compound-bridge-data.ts, src/client/curve/curve-steth/curve-bridge-data.test.ts, src/client/curve/curve-steth/curve-bridge-data.ts, src/client/donation/donation-bridge-data.ts, src/client/element/element-bridge-data.test.ts, src/client/element/element-bridge-data.ts, src/client/example/example-bridge-data.ts, src/client/lido/lido-bridge-data.test.ts, src/client/lido/lido-bridge-data.ts
Docs of bridge-data.ts were incomplete, contained typos and were incorrectly formatted. This is fixed in this PR.
=> Refactored bridge-data.ts + updated docs

src/test/bridges/donation/DonateBridgeE2E.t.sol
=> test: fixed donation bridge test

README.md, package.json, src/aztec/interfaces/IDefiBridge.sol, src/bridges/base/BridgeBase.sol, src/bridges/base/ErrorLib.sol, src/bridges/compound/CompoundBridge.sol, src/bridges/element/ElementBridge.sol, src/bridges/example/ExampleBridge.sol, src/bridges/liquity/StabilityPoolBridge.sol, src/bridges/liquity/StakingBridge.sol, src/bridges/liquity/TroveBridge.sol, src/bridges/set/IssuanceBridge.sol, src/interfaces/IERC20Permit.sol, src/interfaces/IWETH.sol, src/interfaces/aave/IAToken.sol, src/interfaces/aave/ILendingPoolAddressesProvider.sol, src/interfaces/aave/IScaledBalanceToken.sol, src/test/aztec/oracle/OracleHelper.t.sol, src/test/bridges/element/Element.t.sol, src/test/bridges/element/Heap.t.sol, src/test/bridges/element/HeapTestContract.sol, src/test/bridges/liquity/StabilityPoolBridgeInternal.t.sol, src/test/bridges/liquity/StakingBridgeInternal.t.sol, src/test/bridges/set/SetUnit.t.sol
=> License cleanup

.github/pull_request_template.md
=> docs: natspec in checklist

.github/pull_request_template.md
=> docs: expanded checklist

src/bridges/curve/CurveStEthBridge.sol, src/test/bridges/curve/CurveStEthBridge.t.sol
Closes #157 
I updated the use of `_auxData` to make it easier to reason about, always specifying a ratio in the trade direction on curve, e.g., when going eth -> wstETh, the auxData will specify minimum amount of stEth to receive per eth, and when going the opposite direction, minimum amount of eth to receive per steth.
=> make min prices more uniform

README.md, src/aztec/interfaces/IDefiBridge.sol, src/aztec/interfaces/IRollupProcessor.sol, src/bridges/compound/CompoundBridge.sol, src/bridges/curve/CurveStEthBridge.sol, src/bridges/donation/DonationBridge.sol, src/bridges/example/ExampleBridge.sol, src/bridges/lido/LidoBridge.sol, src/bridges/liquity/StabilityPoolBridge.sol, src/bridges/liquity/StakingBridge.sol, src/bridges/liquity/TroveBridge.sol, src/bridges/uniswap/UniswapBridge.sol, src/test/aztec/base/BridgeTestBase.sol, src/test/bridges/example/ExampleUnit.t.sol, src/test/bridges/uniswap/UniswapBridgeInternal.t.sol
=> Updated docs + renamed _inputValue to _totalInputValue

.github/pull_request_template.md
=> chore: updated checklist

package.json
Increase version number for tagged release
=> increase version number

src/aztec/Subsidy.sol, src/aztec/interfaces/ISubsidy.sol, src/bridges/example/ExampleBridge.sol, src/test/aztec/subsidy/Subsidy.t.sol, src/test/bridges/example/ExampleE2E.t.sol, src/test/bridges/example/ExampleUnit.t.sol
Before:
Gas cost of convert function increased by **16701** gas.
After:
Gas cost of convert function increased by **20904** gas.
After:
Gas cost of convert function increased by **45904** gas.
=> Subsidy contract

package.json, src/client/element/element-bridge-data.test.ts, src/client/element/element-bridge-data.ts, yarn.lock
New version of Openzeppelin contracts contains IERC4626 interface which is useful for the ERC4626 bridge so I decided to do the update. I've also moved some deps from devDependencies to dependencies since they are required for build and not only for development.
=> Updated dependencies

src/bridges/dca/BiDCABridge.sol, src/bridges/dca/UniswapDCABridge.sol, src/specs/dca/readme.md, src/test/bridges/dca/BiDCABridge.t.sol
=> refactor + docs: updated docs + some names

src/client/yearn/yearn-bridge-data.test.ts, src/client/yearn/yearn-bridge-data.ts, src/interfaces/yearn/IYearnVault.sol
1. Removed tech debt - replaced `getExpectedYield(...)` with `getAPR(...)`,
2. implemented `getMarketSize(...)`.
=> Updated yearn client

package.json, src/client/aave/aave-bridge-data.ts, src/client/bridge-data.ts, src/client/compound/compound-bridge-data.test.ts, src/client/compound/compound-bridge-data.ts, src/client/curve/curve-steth/curve-bridge-data.ts, src/client/donation/donation-bridge-data.ts, src/client/element/element-bridge-data.ts, src/client/erc4626/erc4626-bridge-data.test.ts, src/client/erc4626/erc4626-bridge-data.ts, src/client/example/example-bridge-data.ts, src/client/lido/lido-bridge-data.ts, src/client/yearn/yearn-bridge-data.test.ts, src/client/yearn/yearn-bridge-data.ts
=> refactor: returning number[] from getAuxData(...)

src/deployment/subsidy/SubsidyDeployment.sol
=> Subsidy deployment script

src/bridges/element/ElementBridge.sol, src/bridges/element/MinHeap.sol, src/interfaces/aave/IAToken.sol, src/interfaces/aave/IAaveIncentivesController.sol, src/interfaces/aave/ILendingPool.sol, src/interfaces/aave/ILendingPoolAddressesProvider.sol, src/interfaces/aave/IPool.sol, src/interfaces/aave/IScaledBalanceToken.sol, src/interfaces/element/ITranche.sol, src/interfaces/element/IVault.sol, src/interfaces/element/IWrappedPosition.sol, src/interfaces/uniswapv3/pool/IUniswapV3PoolDerivedState.sol, src/interfaces/uniswapv3/pool/IUniswapV3PoolImmutables.sol, src/libraries/aave/DataTypes.sol, src/libraries/aave/WadRayMath.sol, src/libraries/uniswapv3/FullMath.sol, src/libraries/uniswapv3/TickMath.sol
I wanted to try whether a feature I needed has been implemented in a newer solc version but it turned out that plenty of the versions are misconfigured across codebase. This PR fixes it.
=> fix: solc versioning

src/client/yearn/yearn-bridge-data.test.ts, src/client/yearn/yearn-bridge-data.ts
=> feat: getUnderlyingAmount in Yearn client

package.json
Use the newest foundry version available again, as their regression was solved.
=> use newest foundry version

README.md
=> Subsidy in Readme

src/deployment/AggregateDeployment.s.sol
=> feat: AggregateDeployment

src/client/yearn/yearn-bridge-data.test.ts, src/specs/dca/readme.md, src/test/bridges/dca/BiDCABridge.t.sol, src/test/bridges/dca/BiDCABridgeArber.t.sol, src/test/bridges/dca/BiDCABridgeE2E.t.sol
The PR contains a DCA arbitrage guide.
=> DCA arbitrage guide

package.json, src/client/dca/dca-bridge-data.test.ts, src/client/dca/dca-bridge-data.ts
Fixed bug in the client's implementation of `getInteractionPresentValue(...)`.
=> DCA client fix

package.json, src/client/erc4626/erc4626-bridge-data.test.ts, src/client/erc4626/erc4626-bridge-data.ts, src/client/euler/euler-bridge-data.test.ts, src/client/euler/euler-bridge-data.ts
Implementation of Euler client.
=> Euler client

package.json, src/client/euler/euler-bridge-data.test.ts, src/client/euler/euler-bridge-data.ts
=> Correctly handling ETH in `getMarketSize(...)` function of Euler client

package.json, src/client/erc4626/erc4626-bridge-data.test.ts, src/client/erc4626/erc4626-bridge-data.ts
Underlying amount in erc4626 client
=> Underlying amount in erc4626 client

src/deployment/AggregateDeployment.s.sol, src/deployment/erc4626/ERC4626Lister.s.sol
- Adds an erc4626 lister script
- Uses the script in aggregate deployment to list euler vaults on bridge
- [] Continuous integration (CI) passes.
=> feat: update aggregate to list vault on erc4626 as well

src/test/aztec/base/BridgeTestBase.sol
=> Test base ending at full slot

src/deployment/dataprovider/DataProviderDeployment.s.sol, src/deployment/erc4626/ERC4626Lister.s.sol
Was missing address printout as well when trying to setup AAVE on testnet so I modified the script.
=> Printing address when reading from data provider

src/gas/base/GasBase.sol
=> Bubbling errors in gasbase

package.json, src/bridges/liquity/TroveBridge.sol, src/client/bridge-data.ts, src/client/liquity/trove-bridge-data.test.ts, src/client/liquity/trove-bridge-data.ts
=> Liquity TroveBridge client

.circleci/config.yml, package.json, src/client/element/element-bridge-data.ts, src/test/bridges/liquity/StabilityPoolBridgeUnit.t.sol
Updated dependencies + fixed CI. The new `forge-std` behaves a bit differently and it broke one Liquity tests so I fixed it. I also changed element client based on the changes in rollup-encoder.
Foundry started crashing so I submitted an [issue](https://github.com/foundry-rs/foundry/issues/3596).
=> Dependency update + publish CI fix

.circleci/config.yml, package.json, src/client/aavev2/aavev2-bridge-data.test.ts, src/client/aavev2/aavev2-bridge-data.ts, src/client/angle/angle-bridge-data.test.ts, src/client/angle/angle-bridge-data.ts, src/client/bridge-data.ts, src/client/curve/curve-steth/curve-bridge-data.test.ts, src/client/curve/curve-steth/curve-bridge-data.ts, src/client/dca/dca-bridge-data.test.ts, src/client/dca/dca-bridge-data.ts, src/client/donation/donation-bridge-data.ts, src/client/element/element-bridge-data.test.ts, src/client/element/element-bridge-data.ts, src/client/erc4626/erc4626-bridge-data.test.ts, src/client/erc4626/erc4626-bridge-data.ts, src/client/euler/euler-bridge-data.test.ts, src/client/euler/euler-bridge-data.ts, src/client/example/example-bridge-data.ts, src/client/lido/lido-bridge-data.test.ts, src/client/lido/lido-bridge-data.ts, src/client/liquity/trove-bridge-data.test.ts, src/client/liquity/trove-bridge-data.ts, src/client/yearn/yearn-bridge-data.test.ts, src/client/yearn/yearn-bridge-data.ts, src/test/bridges/liquity/StabilityPoolBridgeUnit.t.sol
=> bigint auxData in clients

src/test/bridges/dca/BiDCABridgeE2E.t.sol
=> Decreasing bounds to avoid Uni liquidity issues

src/bridges/liquity/TroveBridge.sol, src/deployment/liquity/LiquityTroveDeployment.s.sol, src/gas/liquity/TroveBridgeGas.s.sol, src/test/bridges/liquity/TroveBridgeUnit.t.sol
TroveBridge gas measurements and Subsidy support in TroveBridge.
=> TroveBridge measurement + Subsidy support

src/deployment/base/BaseDeployment.s.sol, src/deployment/dataprovider/DataProviderDeployment.s.sol, src/deployment/liquity/LiquityTroveDeployment.s.sol
- Updates the chainid for the devnet
- List liquity accounting token
- Update address of data provider
=> Liquity deployment fixes

src/deployment/liquity/LiquityTroveDeployment.s.sol, src/gas/liquity/TroveBridgeGas.s.sol
=> Opening Trove in the deployment script of TroveBridge

src/client/compound/compound-bridge-data.test.ts, src/client/compound/compound-bridge-data.ts, src/client/liquity/trove-bridge-data.test.ts, src/client/liquity/trove-bridge-data.ts
1. Returning dummy value on index 0 from `getExpectedOutput(...)` when borrowing,
2. implementation of `getMarketSize(...)`.
=> Updated TroveBridge client

src/deployment/AggregateDeployment.s.sol, src/deployment/dataprovider/DataProviderDeployment.s.sol
Add compound deployment to aggregate script and moves data provider up, such that it should have the same address independent on extra bridges being added between devnet resets.
=> fix: add compound deployment + fix ordering

src/deployment/AggregateDeployment.s.sol, src/deployment/dataprovider/DataProviderDeployment.s.sol
Please provide a paragraph or two giving a summary of the change, including relevant motivation and context.
=> feat: add uniswap bridge + iceth asset

src/deployment/base/BaseDeployment.s.sol, src/test/aztec/base/BridgeTestBase.sol, src/test/bridges/erc4626/ERC4626.t.sol, src/test/bridges/liquity/TroveBridgeE2E.t.sol
Fixes tests after the lister role was introduced and given to another multisig-address.
=> fix: grant lister role to MS + fix gas limits

specs/aztec/dataprovider/readme.md, src/deployment/dataprovider/DataProviderDeployment.s.sol
=> chore: removed `read()` and updates readme.

src/bridges/element/ElementBridge.sol
Fixing some small typos I found while reading the `ElementBridge.sol` contract.
=> Fixed small typos in the ElementBridge contract

src/deployment/AggregateDeployment.s.sol, src/deployment/yearn/YearnDeployment.s.sol
Adds yvLUSD to deployment flow.
=> Add yvLUSD at the end of deployment flow.

package.json
Please provide a paragraph or two giving a summary of the change, including relevant motivation and context.
=> Chore: pin yearn bridge test

src/scripts/FinalisationScript.sol, yarn.lock
A script which finalizes all the interactions defined by its nonce in the interactionNonces array. It uses multicall contract from MakerDAO to make it less gas intensive.
=> FinalisationScript
