AztecProtocol/aztec-connect-bridges

- src/bridges/lido/LidoBridge.sol
- src/client/lido/lido-bridge-data.test.ts
- src/client/lido/lido-bridge-data.ts
- src/test/lido/Lido.t.sol
**Author**
0xinugami
**Description**
This bridge enables users to stake their ETH and earn interest from Lido. The users can also use this bridge to exchange their wstETH back to ETH.
**Usage**
To stake ETH
- Input: ETH
- Output: ERC20 and wstETH address
To get back ETH from wstETH
- Input: ERC20 and wstETH address
- Output: ETH
**Contract Test**
File: `Lido.t.sol`
Run: `forge test -m Lido.t.sol`
**Client Test**
File: `lido-bridge-data.test.ts`
Run: `yarn test:client`
> Add Lido bridge

- src/test/element/Heap.t.sol
Hi,
It requires only a few changes to fuzz your Heap tests with different random arrays.
The default amount fuzz runs can be set in the `foundry.toml` or by setting `FOUNDRY_FUZZ_RUNS`.
> test: added fuzzing to Element Heap tests

- src/bridges/liquity/TroveBridge.sol
- src/test/liquity/TroveBridge.t.sol
Instead of setting max borrower fee in bridge constructor, the fee is now passed to openTrove(...) and convert(...).
> refactor: passing fee in openTrove(...) and convert(...)

- package.json
testRedeemFlow test was currently disabled since it was not passing at the current block height. I pinned it to an older block and now it runs fine.
> test: pinned TroveBridge tests

- hardhat.config.ts
- package.json
- src/aztec/DefiBridgeProxy.sol
- src/aztec/RollupProcessor.sol
- src/bridges/uniswapv3/SyncUniswapV3Bridge.sol
- src/bridges/uniswapv3/UniswapV3Bridge.sol
- src/bridges/uniswapv3/base/LiquidityManagement.sol
I introduced a bug in PR https://github.com/AztecProtocol/aztec-connect-bridges/pull/71 which broke hardhat compilation. This PR fixes it.
The issue with hardhat was that hardhat doesn't have support for remappings. I fixed the compilation issues by forcing Hardhat to ignore test contracts during compilation. From my knowledge we don't need types for tests as tests are not accessed by frontend. If I am mistaken please let me know.
I have removed the console.sol dependency from non-test files. I think it's better to have the console.sol dependency imported only when debugging and during debugging we don't need hardhat compatibility.
> fix: hardhat configuration

- src/bridges/set/IssuanceBridge.sol
- src/bridges/set/interfaces/IController.sol
- src/bridges/set/interfaces/IExchangeIssuance.sol
- src/bridges/set/interfaces/ISetToken.sol
- src/test/set/Set.t.sol
The biggest changes are:
1) Approving tokens once instead of every call --> this is not a vulnerability because the spenders are trusted (issuanceExchange and rollupProcessor) + the bridge never holds any tokens after the interaction is finished;
2) cleaned up logic;
3) improved tests and docs.
> Implemented changes based on Set audit

- README.md
- src/bridges/example/ExampleBridge.sol
- src/test/example/Example.t.sol
I updated the example bridge with new features from forge-std and solidity 0.8.4. It's desirable that grantees use those so I think it's important to have them in the example.
> refactor: updated example bridge + docs

- .solhint.json
- src/bridges/liquity/StabilityPoolBridge.sol
- src/bridges/liquity/StakingBridge.sol
- src/bridges/liquity/TroveBridge.sol
- src/bridges/liquity/interfaces/IBorrowerOperations.sol
- src/bridges/liquity/interfaces/ILQTYStaking.sol
- src/bridges/liquity/interfaces/ILiquityBase.sol
- src/bridges/liquity/interfaces/IPriceFeed.sol
- src/bridges/liquity/interfaces/ISortedTroves.sol
- src/bridges/liquity/interfaces/IStabilityPool.sol
- src/bridges/liquity/interfaces/ISwapRouter.sol
- src/bridges/liquity/interfaces/ITroveManager.sol
- src/bridges/set/IssuanceBridge.sol
- src/bridges/set/interfaces/IController.sol
- src/bridges/set/interfaces/IExchangeIssuance.sol
- src/bridges/set/interfaces/ISetToken.sol
- src/interfaces/IDefiBridge.sol
- src/interfaces/IERC20Permit.sol
- src/interfaces/IRollupProcessor.sol
- src/interfaces/IWETH.sol
- src/test/example/Example.t.sol
- src/test/liquity/StabilityPoolBridge.t.sol
- src/test/liquity/StabilityPoolBridgeInternal.t.sol
- src/test/liquity/StakingBridge.t.sol
- src/test/liquity/StakingBridgeInternal.t.sol
- src/test/liquity/TroveBridge.t.sol
- src/test/liquity/interfaces/IHintHelpers.sol
- src/test/liquity/utils/MockPriceFeed.sol
- src/test/liquity/utils/TestUtil.sol
- src/test/set/Set.t.sol
1. Fixed linting errors in Set tests (the bridge itself didn't contain any issues),
2. fixed linting errors in Liquity bridges and tests,
3. updated solhint config to not warn about using block.timestamp,
4. updated solidity versions in src/interfaces/*,
5. using vm.expectRevert(...) instead of try.. catch,
6. ordered functions in Liquity bridges according to solidity style guide,
7. more concise example test.
> Janb/linting errors in Set and Liquity bridges

- .solhint.json
- package.json
- yarn.lock
Extends solhint with custom rules that:
- Treat `immutable` as `constant` with regard to naming
- Give a warning if not using CamelCase for custom errors
- Give a warning if using require, or empty revert
- Prefer internal/private functions to have a single leading `_`
- Prefer internal/private variables to NOT have a single leading `_`
- Prefer function argument names to have a single leading `_`
> fix: Update solhint to use forked repo with extra rules

- .solhint.json
Adds an extra rule to the solhint file to ensure that function params are mixed case.
> feat: Add func-param-name-mixedcase rule

- src/client/lido/lido-bridge-data.test.ts
- src/client/lido/lido-bridge-data.ts
Update the Lido client data class to use `wstEth` instead of `stEth` in the expected, and remove the curve route to match the underlying Lido bridge.
> fix: Use wstEth in `getExpectedOutput`

- src/interfaces/IDefiBridge.sol
Remove `virtual` from the `IDefiBridge.sol` as they are redundant.
> fix: Remove virtual from IDefiBridge interface

- src/test/bridges/compound/Compound.t.sol
Add a log of `block.number` in the compound, that will make it easier to find the blocks where we run into #119.
> emit block number from compound setup

- src/bridges/compound/CompoundBridge.sol
- src/interfaces/compound/IComptroller.sol
- src/test/bridges/compound/Compound.t.sol
These were the issues mentioned in the audit:
1. The safeIncreaseAllowance() might revert if the current allowance is not 0
>  We've addressed this issue by pre-approving the tokens. There are 2 new methods `preApprove` and `preApproveAll`. `preApproveAll` sets the approvals for all the cTokens from Comptroller and its underlying tokens. `preApprove` sets the approvals for ` cToken and its underlying. By pre-approving the tokens once to the maximum the probability of this issue occurring gets significantly diminished.
2. Only allow valid cToken contracts from Compound
> We've decided that this is not an issue because the bridge doesn't have any state.
> Implementation of changes based on the Compound audit

- .solhint.json
I want grantees to fix linting errors/warnings without our feedback and I've just noticed that linter doesn't return exit code 1 on warnings. This is necessary for CI to fail. For this reason I changed warnings to be errors in the solhint config.
> Make linter throw errors on everything to enforce it in CI

- src/bridges/curve/CurveStEthBridge.sol
- src/test/bridges/curve/CurveStEthBridge.t.sol
Passing minPrice to CurveStEthBridge through _auxData in order to set slippage protection while not breaking aggregation.
> Slippage protection in CurveStEthBridge

- src/test/bridges/liquity/StabilityPoolBridgeInternal.t.sol
- src/test/bridges/liquity/StabilityPoolBridgeUnit.t.sol
- src/test/bridges/liquity/StakingBridgeInternal.t.sol
- src/test/bridges/liquity/StakingBridgeUnit.t.sol
- src/test/bridges/liquity/TroveBridge.t.sol
- src/test/bridges/liquity/TroveBridgeUnit.t.sol
- src/test/bridges/liquity/utils/MockPriceFeed.sol
- src/test/bridges/liquity/utils/TestUtil.sol
Updated tests to call bridge convert function directly. I plan on adding E2E tests in a separate PR. I created an issue for that https://github.com/AztecProtocol/aztec-connect-bridges/issues/152.
> Updated liquity tests to not use mocked RollupProcessor

- src/test/aztec/base/BridgeTestBase.sol
- src/test/aztec/base/EncodeBridgeId.t.sol
Closes #160 
Extends the `BridgeTestBase::encodeBridgeId` to better handle virtual assets without users having to manually account for it in the id.
Also adds tests for encoding virtual and non-virtual assets.
> handle virtual assets in encodeBridgeId helper

- src/client/aave/aave-bridge-data.test.ts
- src/client/aave/aave-bridge-data.ts
- src/client/bridge-data.ts
- src/client/compound/compound-bridge-data.test.ts
- src/client/compound/compound-bridge-data.ts
- src/client/curve/curve-steth/curve-bridge-data.test.ts
- src/client/element/element-bridge-data.test.ts
- src/client/element/element-bridge-data.ts
- src/client/lido/lido-bridge-data.test.ts
I refactored clients so that `EthAddress` type is used in `AztecAsset`. This makes a lot of sense because clients are used in the internal codebase and there the use of `EthAddress` type is the default.
> refactor: using EthAddress type in AztecAsset

- .circleci/config.yml
- .eslintrc.js
- package.json
- src/client/bridge-data.ts
- src/client/element/element-bridge-data.test.ts
- src/client/element/element-bridge-data.ts
- yarn.lock
Changes in this PR:
1. Configuring ESLint and running it in CI,
2. updated dependency versions,
3. renamed `test:client` command to `test:clients` because contracts are tested as `test:contracts`,
4. I configured ESLint to not throw error when camel case is not followed because typechain generates factory files which don't follow camel case (e.g. `IRollupProcessor__factory`). I would like this enforced but I also don't mind how typechain names the factories so I decided to not enforce it for now.
> Configured ESLint + updated dependencies

- src/client/bridge-data.ts
- src/client/curve/curve-steth/curve-bridge-data.test.ts
- src/client/curve/curve-steth/curve-bridge-data.ts
- src/client/lido/lido-bridge-data.test.ts
- src/client/lido/lido-bridge-data.ts
Extends the bridge data class with a `getUnderlyingAmount()` function that can be used by the frontend for valuing wrapped assets. For `wstEth` this will return the `stEth` amount that it can be unwrapped to, which might help the frontend to simplify explanations for users.
> feat: add `getUnderlyingAmount` to curve-bridge-data

- src/aztec/Subsidy.sol
- src/aztec/interfaces/ISubsidy.sol
- src/test/aztec/subsidy/Subsidy.t.sol
Addressed in 28a760d7e4c41b3201cc3564644ea9f09b9edc1e
Addressed in a0855c8286af2913255ea32eec90cda47d1afaaf
This is not that big of a deal since the intention of subsidy is to simply incentivize rollup provider to include a bridge call with low amount of aggregated users, or more clearly said, low amount of overall fees to be collected. The goal is not to cover `gasUsage` in full. For this reason we've decided to not address this. This issue also gets alleviated by implementing the `topUp(...)` function.
We decided to not address this as well because it would require us to track owner of a Subsidy. Allowing this doesn't seem to be worth the added complexity. Preferable approach is to initially fund subsidy with small ETH amount and let it run out if it's considered that `gasPerMinute` was …
> Subsidy audit feedback implementation

- package.json
- src/client/aave/aave-bridge-data.test.ts
- src/client/aave/aave-bridge-data.ts
- src/client/bridge-data.ts
- src/client/compound/compound-bridge-data.test.ts
- src/client/compound/compound-bridge-data.ts
- src/client/curve/curve-steth/curve-bridge-data.test.ts
- src/client/curve/curve-steth/curve-bridge-data.ts
- src/client/donation/donation-bridge-data.ts
- src/client/element/element-bridge-data.test.ts
- src/client/element/element-bridge-data.ts
- src/client/erc4626/erc4626-bridge-data.test.ts
- src/client/erc4626/erc4626-bridge-data.ts
- src/client/example/example-bridge-data.ts
- src/client/lido/lido-bridge-data.test.ts
- src/client/lido/lido-bridge-data.ts
- src/client/yearn/yearn-bridge-data.test.ts
- src/client/yearn/yearn-bridge-data.ts
1. Simplified `getAPR` function,
2. changed `assetId` type to number,
3. changed `auxData` type to number,
4. importing `AssetValue` from internal repo and doing the related changes,
5. removed `getMarketSize` from element because it was returning non-sense which makes me thing it was not used anyway,
6. changed `interactionNonce` type to number,
7. updated `yarn build` command to not compile typechain twice,
8. removed unused imports and variables from a few places.
> refactor: simplified APR function + unifying AssetValue with internal repo

- src/client/bridge-data.ts
- src/client/element/element-bridge-data.test.ts
- src/client/element/element-bridge-data.ts
1. Element client implements from BridgeDataFieldGetters again,
2. changed nonce type to number in Element,
3. `getAPR(...)` function renamed to `getTermAPR(...)` in order to avoid collision with `BridgeDataFieldGetters.getAPR(...)` which has fewer input params than is needed by Element one.
Note: `getTermAPR(...)` returns `Promise<number>` instead of `Promise<[number]>`.
> refactor: Element inheriting from BridgeDataFieldGetters

- hardhat.config.ts
- src/deployment/curve/CurveDeployment.s.sol
- src/deployment/uniswap/UniswapDeployment.s.sol
- src/deployment/yearn/YearnDeployment.s.sol
- src/gas/base/GasBase.sol
- src/gas/curve/CurveGas.s.sol
- src/gas/yearn/YearnGas.s.sol
A base that allows better gas-estimations of defi interactions. Example written for yearn. 
The measurements is a little tricky as foundry by default tries to cram everything in one tx, so much storage is touched. To work around it, we are using a script to broadcast it, the traces from the broadcast can then be used as an estimate. If not adding the `--broadcast` flag when executing the script, the tx will not be published practically, otherwise can be done against an anvil network.
> measure gas bridges

- src/bridges/base/BridgeBase.sol
- src/bridges/erc4626/ERC4626Bridge.sol
- src/bridges/example/ExampleBridge.sol
- src/bridges/yearn/YearnBridge.sol
- src/deployment/example/ExampleDeployment.s.sol
- src/gas/yearn/YearnGas.s.sol
- src/test/aztec/base/BridgeTestBase.sol
- src/test/bridges/erc4626/ERC4626.t.sol
- src/test/bridges/example/ExampleE2E.t.sol
- src/test/bridges/example/ExampleUnit.t.sol
- src/test/bridges/yearn/YearnBridgeE2E.t.sol
1. Updated ExampleBridge with mainnet Subsidy deployment,
2. fixed bug in example test,
3. fixed ExampleDeployment due to changes after rebase,
4. integrated Subsidy to ERC4626 bridge,
5. simplified Yearn bridge and integrated Subsidy in it.
> Integrating mainnet Subsidy deployment in bridges

- src/deployment/base/BaseDeployment.s.sol
- src/deployment/yearn/YearnDeployment.s.sol
- src/test/bridges/yearn/YearnBridgeE2E.t.sol
Update gas constraints in the yearn tests + deployment.
> list yearn bridge for both deposit/withdraw, as gas differs

- src/test/bridges/element/Element.t.sol
Updating the number of optimizer runs broke the Element test as it looks for an exact gas amount.
> fix expected gas usage values

- src/client/element/element-bridge-data.test.ts
- src/client/element/element-bridge-data.ts
Fetch the eth tx hash for a given interaction nonce via falafel instead of scanning for it via infura.
> More efficient interactionNonce -> ethTxHash

- src/deployment/base/BaseDeployment.s.sol
Replaces the hardcoded addresses in the `BaseDeployment.s.sol` script to use the FFI cheatcode to fetch latest rollup processor addresses for the dev- and testnets. Deployment scripts need to use `--ffi` to get this properly.
Also using `createSelectFork` to simplify deployments
Quality of life improvement.
> Fetch address from status endpoint for dev and testnets

- src/aztec/DataProvider.sol
- src/aztec/interfaces/IRollupProcessor.sol
- src/client/aztec/data-provider/DataProvider.ts
- src/deployment/AggregateDeployment.s.sol
- src/deployment/base/BaseDeployment.s.sol
- src/deployment/dataprovider/DataProviderDeployment.s.sol
- src/deployment/yearn/YearnDeployment.s.sol
- src/test/aztec/dataprovider/DataProvider.t.sol
Adds a data provider that can be used to more easily find the bridgeAddressId or assetIds based on labels.
> Add data provider

- src/aztec/DataProvider.sol
- src/deployment/dataprovider/DataProviderDeployment.s.sol
- src/test/aztec/dataprovider/DataProvider.t.sol
Adds a function to add multiple bridges and assets at once to the data provider.
> Feat: update tags for multiple assets and bridges at once

- src/aztec/DataProvider.sol
- src/deployment/dataprovider/DataProviderDeployment.s.sol
- src/test/aztec/dataprovider/DataProvider.t.sol
Fixes a flag in the Data Provider where not all assets were returned by the `getAssets()` getter because of the offset by the Eth base asset.
> fix: add +1 for assets length to fetch eth asset as well

- src/test/aztec/base/BridgeTestBase.sol
- src/test/aztec/base/BridgeTestBase.t.sol
When bridge finalises interactions from its `convert(...)` function more than 1 `DefiBridgeProcessed` events get emitted which caused `_getDefiBridgeProcessedData()` function to revert. This PR fixes it.
> Handle multiple DefiBridgeProcessed events in `sendDefiRollup(...)`

- src/deployment/AggregateDeployment.s.sol
- src/deployment/erc4626/ERC4626Deployment.s.sol
Extends the aggregate deployment script to deploy the ERC4626 bridge + add euler erc4626 wrappers from timeless for dai, weth and wsteth.
> fix: extend aggregate to include euler

- package.json
- src/client/euler/euler-bridge-data.test.ts
- src/client/euler/euler-bridge-data.ts
Stacking lido's apr on top of euler's when the underlying is wstETH.
@joss-aztec The bridge class takes into consideration the lido yield if you create its instance with `createWithLido` function. I had to do it like this because the class is extending `ERC4626BridgeData` and it's not allowed by typescript to override a parent's class without keeping its arguments.
> Stacking lido's apr on top of euler's

- src/test/aztec/base/BridgeTestBase.sol
@LHerskind Fixed the cause of the bug the hackathon participants were facing yesterday. We should be more careful with SLOADing in YUL because it tends to cause these bugs which are shitty to debug.
> rollupBeneficiary slot packing fix in BridgeTestBase

- package.json
- src/client/aavev2/aavev2-bridge-data.test.ts
- src/client/aavev2/aavev2-bridge-data.ts
Implementation of AAVE v2 client.
The value returned by `getMarketSize(...)` is lower than the one in AAVE's UI (e.g. for Dai it's 140M vs 200M). I think the reason is that in AAVE UI they show for all the protocol versions and not just for v2. I asked on [Discord](https://discord.com/channels/602826299974877205/636902500041228309/1031876343706689566) and will update it if needed. I think it's good idea to merge this now so that @joss-aztec has a client to work with ASAP.
> AAVE v2 client

- src/deployment/AggregateDeployment.s.sol
- src/deployment/erc4626/ERC4626Deployment.s.sol
- src/deployment/liquity/LiquityTroveDeployment.s.sol
1. Listing AAVE wrappers,
2. Liquity TroveBridge deployment in Aggregate,
3. removed Euler wrapper deployment on testnet since testnet will get forked from a newer block which should have it deployed.
> Liquity deployment + AAVE v2 ERC4626 wrapper listing

- src/deployment/AggregateDeployment.s.sol
- src/deployment/dataprovider/DataProviderDeployment.s.sol
- src/test/bridges/erc4626/ERC4626.t.sol
- src/test/bridges/liquity/StabilityPoolBridgeUnit.t.sol
- Update usage of `bound` to use more precise lower limits. After the `forge-std` update, could more easily hit large values, which made forge crash with overflow.
- Updates ordering of aggregate deployment to have parity with mainnet.
> Fix `bounds` and ordering

- src/client/element/element-bridge-data.test.ts
The element client test mocks the wrong class, so test tries to fetch from non-existing contract and provider.
> fix element client test

- package.json
- src/bridges/liquity/TroveBridge.sol
- src/test/bridges/liquity/TroveBridgeE2E.t.sol
- src/test/bridges/liquity/TroveBridgeTestBase.sol
- src/test/bridges/liquity/TroveBridgeUnit.t.sol
Since it turned out that having 2 assets on input can be tricky UX-wise I am adding an option of repaying the debt only with user's collateral in this PR. This will result in users having the option to repay debt by only providing TB on input (and not LUSD). To achieve this flash swaps are used.
> Repaying LUSD debt with collateral in TroveBridge

- src/aztec/DataProvider.sol
- src/deployment/AggregateDeployment.s.sol
- src/deployment/dataprovider/DataProviderDeployment.s.sol
- src/test/aztec/dataprovider/DataProvider.t.sol
Returns the number of gas units as well as the eth subsidized for `getAccumulatedSubsidyAmount`
> Add gas units to data provider return value

- src/bridges/liquity/TroveBridge.sol
- src/test/bridges/liquity/TroveBridgeUnit.t.sol
Implementation of changes based on second `TroveBridge` audit feedback.
1. Fixed the underflow bug,
2. improved naming as recommended in the audit report,
3. fixed "overshadow" bug found by a test.
> Second TroveBridge audit feedback

- package.json
- src/client/element/element-bridge-data.test.ts
- src/client/element/element-bridge-data.ts
[This PR ](https://github.com/AztecProtocol/aztec2-internal/pull/1681) is adding new APIs that will replace graphQL functionality. 
Updating logic here to use new APIs. Once this is merged & released, we can remove graphQL altogether from falafel
Setting this as "draft" until new Falafel APIs are released
> upgrade element bridge to use falafel's new REST API

- src/bridges/uniswap/UniswapBridge.sol
- src/gas/uniswap/UniswapGas.s.sol
Implemented Subsidy support in UniswapBridge + gas measurement.
@LHerskind I set the subsidy params (gasUsage, minGasPerMinute) based on the 1 split path swap gas usage which is 300k gas. When 2 split paths are used the bridge consumes 430k gas. I think it's ok to have it based only on the 1 split path swap since it will be the most common case and it's not so important to have the subsidy params precise. If you disagree I could work around that by having a different set of criteria for 1 split path swaps and 2 split path swaps.
> Subsidy support in UniswapBridge

- src/gas/liquity/TroveBridgeGas.s.sol
- src/test/bridges/liquity/TroveBridgeE2E.t.sol
Unfortunately interactions with Liquity are not constant gas-wise. The cause of this might be the fact that upon trove adjustment Liquity is looking for a new position in the sorted list of troves (on [this line](https://github.com/PolyQuity/contracts/blob/main/BorrowerOperations.sol#L303)). In this PR I adjusted the measurements to the current value. If the gas consumption rises again TroveBridge test should fail.
> Updated TroveBridge measurements

- foundry.toml
- src/aztec/Subsidy.sol
- src/bridges/angle/AngleSLPBridge.sol
- src/bridges/base/BridgeBase.sol
- src/bridges/curve/CurveStEthBridge.sol
- src/bridges/dca/BiDCABridge.sol
- src/bridges/dca/UniswapDCABridge.sol
- src/bridges/donation/DonationBridge.sol
- src/bridges/element/ElementBridge.sol
- src/bridges/erc4626/ERC4626Bridge.sol
- src/bridges/example/ExampleBridge.sol
- src/bridges/lido/LidoBridge.sol
- src/bridges/liquity/StabilityPoolBridge.sol
- src/bridges/liquity/StakingBridge.sol
- src/bridges/liquity/TroveBridge.sol
- src/bridges/uniswap/UniswapBridge.sol
- src/bridges/yearn/YearnBridge.sol
- src/deployment/liquity/LiquityTroveDeployment.s.sol
- src/gas/angle/AngleSLPGas.s.sol
- src/gas/erc4626/ERC4626Gas.s.sol
- src/gas/liquity/TroveBridgeGas.s.sol
- src/gas/uniswap/UniswapGas.s.sol
- src/test/bridges/erc4626/mocks/WETHVault.sol
- src/test/bridges/liquity/TroveBridgeE2E.t.sol
- src/test/bridges/liquity/utils/MockPriceFeed.sol
With the new foundry version there is no longer a space after override anywhere. This caused grantee's CI to not pass. I think it makes sense to use the new default style.
> style: updated formatting

- README.md
- specs/aztec/dataprovider/readme.md
- src/deployment/base/BaseDeployment.s.sol
Small tidy-up pr to capitalise the two env vars:
- simulateAdmin -> SIMULATE_ADMIN
- network -> NETWORK
> cleanup: capitalize env vars

- package.json
To get around failing tests because of low liquidity, I have pinned the BiDCA bridge tests to a time with liquidity. Removed a few unneeded imports as well.
> fix: pin BiDCA tests to block 14950000

- README.md
- local_devnet/docker-compose.fork.yml
- local_devnet/export_addresses.sh
Update the documentation to get the local devnet running, include helper script to view contract addresses and pre-populate path with values required to make deployments.
> docs: update readme to mention local devnet setup

- package.json
Pins the tests that were not already pinned to get around the hurdle of property tests exhausting liquidity pools etc.
> fix: pin block for tests
